### ISSUE TITLE
Add `revalidateMode` prop to `Form`

### ISSUE THREAD

**Issue by johnsonthedev** [SeasonedSoftware/remix-forms#30]
this is regarding: https://remix-forms.seasoned.cc/examples/actions/field-error

If I enter foo@bar.com and submit the form it returns with **Email already taken**. => Ok
If I change the email to **foo** the error changes to **Invalid email** without requiring a submit => not sure if this is a bug or a feature. I think it should only re-validate if I use **mode="onChange"**
If I now change the email to a valid one like remix@foo.com the old/cached error appears:  **Email already taken**  => Not Ok. I think this is confusing, as it might lead to the assumption that remix@foo.com is taken too. 

My proposal would be to allow resetting errors

**Comment by danielweinmann** [comment]
Thanks @johnsonthedev! My suggestion for this issue is:

1. Add a `revalidateMode` prop to `Form` and pass it to react-hook-form's [useForm](https://react-hook-form.com/api/useform). Right now, we're always using the `onChange` default for revalidation.

2. Reset server-side errors upon revalidation.

How does that sound to you?

We'll work on this soon, but it probably won't be a top priority. Feel free to send a PR in the meantime :) thank you!

**Comment by danielweinmann** [comment]
We'll track the server-side revalidation on #111 and use this issue only for adding the `revalidateMode` to `Form`.
