### ISSUE TITLE
How to handle error on resource route?

### ISSUE THREAD

**Issue by alexluong** [SeasonedSoftware/remix-forms#55]
Hi, I'm just wondering if there's a good way to use `formAction` in a resource route.

My use case is that I have a page with multiple different forms. Ideally, each of the forms will be handled by a resource route for reusability. I imagine the behavior would be each resource route will redirect back to the original page with the errors somehow and the form can pick it up and display the error message correctly. I'm not sure if this is technically possible (maybe with a form prefix?).

I'm just wondering if I'm missing something here. Would love to hear your thoughts! Thanks

**Comment by danielweinmann** [comment]
Hey, @alexluong!

If you use a resource route + [useFetcher](https://remix-forms.seasoned.cc/examples/forms/use-fetcher), it will work out of the box with as many forms as you'd like on your original page.

As far as I can understand, Remix resource routes are not intended to be used for navigational purposes (without useFetcher, for example).  If you try to navigate from a resource route, Remix will ask you to add a route component to the route, making it not a resource route anymore :)

But if you really want to use a resource(ish) route but not useFetcher, you need a way to send the data back to the original page in case of errors. If I were to do that (and I wouldn't 🙂), I would add the errors returned from [performMutation](https://remix-forms.seasoned.cc/examples/actions/custom-response) + the values from the input to the query string when redirecting to the original page. Then, I would get them from the query string on my `loader` and pass them to `<Form schema={schema} errors={errors} values={values}`. Plus, I would add something to the query string to let my loader know which form was returning the error.

This feels like an anti-pattern to me. In Remix, if you want to have multiple forms on the same page and render errors correctly, I think you have three patterns to pick from:

1. You use navigation (regular forms) to the same route, with some form to indicate to the `action` which form is being submitted.
2. You useFetcher and have multiple resource routes dealing with each form. In this pattern, you're going to have to work a little harder if you want Progressive Enhancement.
3. Depending on your use case, you can use nested layouts to render each form as part of a different layout. That way you can have regular, navigational, forms with an `action` that only deals with one form.

How does that sound to you? I'm closing this issue because it doesn't feel like we need to do something about this at this moment. But feel free to reopen it if you need additional support or disagree in any way :)

**Comment by alexluong** [comment]
Thanks for the detailed response. I totally forgot about useFetcher for a moment there. Appreciate the quick response and the awesome library, really enjoying it so far!

**Comment by danielweinmann** [comment]
Thanks, @alexluong! I appreciate it 💪🏼 🙏🏼
