### ISSUE TITLE
Infer email type from zod schema?

### ISSUE THREAD

**Issue by fritzblue** [SeasonedSoftware/remix-forms#81]
If the zod schema says something is an email, could the input field infer the `email` type?

If not, could the `type` field be made easier to override without reaching for an entirely custom input?

**Comment by danielweinmann** [comment]
We don't want to enforce this pattern on people, but we want to make it easy for users to achieve this. I created #83 with an idea of how to make it easier in the future. With that said, there are a couple of solutions today:

### One-off solution for a single form

```ts
<Form schema={schema}>
  {({ Field, Errors, Button }) => (
    <>
      <Field name="email" type="email" />
      <Errors />
      <Button />
    </>
  )}
</Form>
```

### Project-wide solution on your [custom Form component](https://remix-forms.seasoned.cc/get-started)

```ts
import type { FormProps } from 'remix-forms'
import { Form as RemixForm } from 'remix-forms'
import type { SomeZodObject } from 'zod'

export default function Form<Schema extends SomeZodObject>(
  props: FormProps<Schema>,
) {
  return (
    <RemixForm<Schema>
      renderField={({ Field, shape, ...props }) => {
        const checks = shape._def?.checks || []

        const isEmail = checks.some(
          ({ kind }: Record<string, string>) => kind === 'email',
        )

        return (
          <Field
            type={isEmail ? 'email' : undefined}
            shape={shape}
            {...props}
          />
        )
      }}
      {...props}
    />
  )
}
```

IMPORTANT: This last solution is partial. It will not work if your `z.string().email()` also has a `min(1)` or any other refinements. To achieve a complete solution, you'd have to introspect the `shape` with a recursive function like [shapeInfo](https://github.com/SeasonedSoftware/remix-forms/blob/main/packages/remix-forms/src/shapeInfo.ts). That's why I created #83 to make it easier to achieve this project-wide solution.

I'm closing this issue but feel free to reopen it at any time :)
