### ISSUE TITLE
CSRF Protection

### ISSUE THREAD

**Issue by arjunyel** [SeasonedSoftware/remix-forms#82]
Does remix-forms have any CSRF protection built-in? If not, I recommend integrating the one from remix-utils https://github.com/sergiodxa/remix-utils#csrf

**Comment by danielweinmann** [comment]
We don't add CSRF protection out of the bat, but we support it in the following way:

1. You can pass the `beforeAction` parameter to `formAction` to verify authenticity beforehand. I recommend creating a project-wide `formAction` abstraction with this that you use instead of importing directly from Remix Forms. That way, all your form actions will be protected.

2. You can pass the `beforeChildren` prop to your project-wide [custom Form component](https://remix-forms.seasoned.cc/get-started) and render the authenticity input there, like `beforeChildren={<YourAuthenticityInput />}. That would add the input to all your forms.

I'm closing the issue for now, but feel free to reopen it at any time.

**Comment by arjunyel** [comment]
> We don't add CSRF protection out of the bat, but we support it in the following way:
> 
> 1. You can pass the `beforeAction` parameter to `formAction` to verify authenticity beforehand. I recommend creating a project-wide `formAction` abstraction with this that you use instead of importing directly from Remix Forms. That way, all your form actions will be protected.
> 2. You can pass the `beforeChildren` prop to your project-wide [custom Form component](https://remix-forms.seasoned.cc/get-started) and render the authenticity input there, like `beforeChildren={<YourAuthenticityInput />}`. That would add the input to all your forms.
> 
> I'm closing the issue for now, but feel free to reopen it at any time.

Would you accept a PR that added this by default?

**Comment by danielweinmann** [comment]
What's the API you have in mind?
