### ISSUE TITLE
InputError is ignored when using the action property on form

### ISSUE THREAD

**Issue by johnsonthedev** [SeasonedSoftware/remix-forms#86]
Hi, it seems that InputErrors are ignored when using the action property on a form. 

Here is a stackblitz: https://stackblitz.com/edit/node-a3zkrf?file=app%2Fschema1.tsx

Is this a bug or did i something wrong? 

Thanks :)

**Comment by danielweinmann** [comment]
Hey, @johnsonthedev!

Remix Forms uses `useActionData` under the hood to get the result of `formAction`. But because you're sending the user to `/form1` and running `formAction` inside that route, the action data will only be accessible on the route component inside `form1.tsx`.

There are a few ways of accomplishing what you're looking for. The best one for me is to [useFetcher](https://remix-forms.seasoned.cc/examples/forms/use-fetcher) in both forms.

Then, if progressive enhancement is important for you, you can render each form again on their route component (`form1.tsx` and `form2.tsx` default exports), this time without a fetcher. That way, when the user submits one of the forms with JS disabled, it is redirected to the form's page, and because you're rendering the form there as well, they can see the error message.

I'm closing the issue but feel free to reopen it anytime.

**Comment by johnsonthedev** [comment]
thank you for the quick answer . will  try this out
